baseurl = "http://kutarobo.github.io/growth-diary"
title = "타이틀(연습중)"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "ko-kr"
copyright = "Code released under the Apache 2.0 license."
googleAnalytics = "UA-123-45" # delete or comment to disable Google Analytics JS generation
disqusShortname = "shortname??" #delete or comment to disable Disqus comments

[author]
  name = "kutarobo"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "내 site description 임"
  Author = "kutarobo"
  email = "kutarobo@naber.com" #Remove this line if you would prefer not to use an email button in the footer.
  postSummariesFrontPage = 4 #Number of post summaries to show on front page, comment out to allow default(4)
  showReadTime = true #set to false to exclude read time from header of post
  # This will load all the CSS defined in the list
  customCSS = ["<absolute path to CSS>", "/static/css/test.css", "<or just load it off the internet>"]
  
[[params.social]]
  title = "github"
  url = "https://github.com/kutarobo"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/kutarobo"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
